### ISSUE TITLE
Current weather is invisible

### ISSUE THREAD

**Issue by jwsp1** [sanderbaas/WeatherWidget#24] opened 2019-11-06 07:15 UTC
The widget removes the weather preview picture for the current 3-hours-preview automatically after current time passes a full 3-hour step.
E.g. the weather icon for 7:00-9:59AM gets removed at 7:01AM so I don't know the current weather anymore.
![Screenshot_20191106_081423](https://user-images.githubusercontent.com/24477557/68276503-773ad100-006d-11ea-890a-ade13606452a.jpg)

**Comment by sanderbaas** [comment] 2019-11-06 07:52
Duplicate of #14

**Closed** 2019-11-06 07:53 UTC
